### ISSUE TITLE
Some states (KY, maybe others) are missing from allData

### ISSUE THREAD

**Issue by guillermokrh** [NatashaRice2018/CS-424-Project-3#26]
I noticed that KY is missing from the data set.  It is not available in Natasha's drop down menu and when I select Kentucky as the comparison state, I get a "undefined columns selected error".  When I check the CSV, I see that there are KY tornados in the data set.

**Comment by NatashaRice2018** [comment]
A bunch of states seem to be getting removed in howtomakeRdatafile on these lines

`fips <- read.table('FIPS code',sep = ',')
names(fips)[1]<-'st'
names(fips)[3]<-'f1'
names(fips)[4]<-'county'
allData <- merge(allData,fips,by=c('st','f1'))`

I think @mimiyang wrote them so she may know why?
